{"version":3,"file":"errors.js","sourceRoot":"","sources":["../src/errors.ts"],"names":[],"mappings":";;AAAA,SAAS,aAAa,CAAC,OAAgB;IACrC,IAAI,CAAC,IAAI,GAAG,eAAe,CAAC;IAC5B,IAAI,CAAC,OAAO,GAAG,OAAO,IAAI,gCAAgC,CAAC;IAC3D,IAAI,CAAC,KAAK,GAAG,CAAC,IAAI,KAAK,EAAE,CAAC,CAAC,KAAK,CAAC;AACnC,CAAC;AACD,aAAa,CAAC,SAAS,GAAG,MAAM,CAAC,MAAM,CAAC,KAAK,CAAC,SAAS,CAAC,CAAC;AACzD,aAAa,CAAC,SAAS,CAAC,WAAW,GAAG,aAAa,CAAC;AAEpD,kBAAe,EAAE,aAAa,eAAA,EAAE,CAAC","sourcesContent":["function UnderrunError(message?: string) {\n  this.name = 'UnderrunError';\n  this.message = message || 'An underrun error has occurred';\n  this.stack = (new Error()).stack;\n}\nUnderrunError.prototype = Object.create(Error.prototype);\nUnderrunError.prototype.constructor = UnderrunError;\n\nexport default { UnderrunError };\n"]}